### ISSUE TITLE
The web for searching has died

### ISSUE THREAD

**Issue by npes87184** [sh1r0/NovelDroid#2]
https://googledrive.com/host/0By9mvBCbgqrycV9naFJSYm5mbjQ

Looks like the file has been deleted?

http://imgur.com/a/YlArp

**Comment by sh1r0** [comment]
Google has stopped the web hosting service of google drive. Please refer to https://gsuite-developers.googleblog.com/2015/08/deprecating-web-hosting-support-in.html.

**Comment by npes87184** [comment]
Perhaps you can try github page service?

reference (project site): https://pages.github.com/
