### ISSUE TITLE
卡X諾突然不能下載

### ISSUE THREAD

**Issue by willy208** [sh1r0/NovelDroid#6]
最近卡X諾的小說下載後，

會直接跳過"處理中... 請稍後"的步驟，

下載下來的TXT檔，大小都是0、都沒有內容

以上回報，感謝大大

**Comment by npes87184** [comment]
Hi, @willy208 

It has been fixed at #5.

You can build it yourself or waiting for @sh1r0.

Thanks

**Comment by sh1r0** [comment]
Hi @willy208, [1.5.2](https://github.com/sh1r0/NovelDroid/releases/tag/1.5.2) is released, please have a try, thanks.
